# Site settings
title: Florida Suncoast Helicopters
description: "Just when you didn't think Jekyll could get any better, it got materialized."
url: "https://joncoop.github.io/fsh"
collections:
  inventory:
    output: true

# Build settings
markdown: kramdown

email: info@floridasuncoasthelicopters.com
