# Site settings
title: Jekyll + Materialize = <3
description: "Just when you didn't think Jekyll could get any better, it got materialized."
url: "https://joncoop.github.io/fsh/" # the base hostname & protocol for your site
destination: ../fsh/

# Build settings
markdown: kramdown
