# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Florida Suncoast Helicopters
description: > # this means to ignore newlines until "baseurl:"
  Florida Suncoast Helicopters is Sarasota’s longest established and most trusted helicopter operation and also one of the largest helicopter operations in all of Florida. Suncoast Helicopters is also consistently one of Robinson’s largest dealers in the World. We offer competitive, unparalleled support whether it be for sightseeing tours, flight training or the purchase of a new helicopter. We also are a FAA 145 approved maintenance shop for all your Robinson needs.
baseurl: "" # the subpath of your site, e.g. /blog
url: "floridasuncoasthelicopters.com"

# business info
email: info@floridasuncoasthelicopters.com
phone: 941-355-1259

# social
facebook: https://www.facebook.com/Florida-Suncoast-Helicopters-167594603293714/
instagram: https://www.instagram.com/fshelicopters/
twitter: https://twitter.com/suncoastheli
youtube: https://www.youtube.com/c/Floridasuncoasthelicopters

# Build settings
markdown: kramdown

# Additional content
collections:
  inventory:
    output: true
